### ISSUE TITLE
404 Not Found at plugin configuration

### ISSUE THREAD

**Issue by burg-md** [Nix-wie-weg/redmine_follow_up#1]
While trying to acces the plugin config via the admin panel we occur an 404 error.

Log:
Started GET "/settings/plugin/follow_up" for 192.168.0.25 at 2015-09-08 11:21:36 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"follow_up"}
  Current user: mm (id=3)
  Rendered settings/plugin.html.erb within layouts/admin (1.1ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.1ms)
Completed 404 Not Found in 48ms (Views: 42.9ms | ActiveRecord: 0.4ms)

Environment:
  Redmine version                3.1.0.stable.14485
  Ruby version                   1.9.3-p0 (2011-10-30) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem  
Redmine plugins:
  follow_up                      0.0.1

**Comment by svenwin** [comment]
Oh yeah. This thing was never tested on Version 3 of Redmine as I'm stuck with ChiliProject 2. 

I'm going to give it a try and see if I can come up with anything.

**Comment by burg-md** [comment]
That would be nice, thank you in advance !
